import React, { ReactNode } from "react";
import "./globals.css";
import { CartProvider } from "../../context/CartContext";
import { WishlistProvider } from "../../context/WIshlistContext";

import { Toaster } from "react-hot-toast";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { ScrollProvider } from "../../context/ScrollContext";
import { Quicksand, Fraunces } from "next/font/google";
import Script from "next/script";
import type { Metadata } from "next";
import "./embla.css"
/* -------------------- Fonts -------------------- */

const quicksand = Quicksand({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-quicksand",
});

const fraunces = Fraunces({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-fraunces",
});

/* -------------------- Metadata -------------------- */

export const metadata: Metadata = {
  title: "Bookstore",
  description: "Generated by create next app",
};

/* -------------------- Layout -------------------- */

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <>
      <html
        lang="en"
        className={`${quicksand.variable} ${fraunces.variable}`}
      >
        <body
          suppressHydrationWarning
          className="flex min-h-screen w-full flex-col bg-primary "
        >

          <Toaster />

          <CartProvider>
            <WishlistProvider>
              <ScrollProvider>
                <Navbar />
                {children}
              </ScrollProvider>
            </WishlistProvider>
          </CartProvider>


          <Footer />

        </body>
      </html>

      <Script
        src="https://checkout.razorpay.com/v1/checkout.js"
        strategy="afterInteractive"
      />
    </>
  );
}
